version: '3'

services:
  db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=payment_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  zookeeper:
    image: 'bitnami/zookeeper'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka'
    volumes:
      - 'kafka_data:/bitnami'
    hostname: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  notification-service:
    image: shahabi0/notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - kafka

  payment-service:
    image: shahabi0/payment-service
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

